### ISSUE TITLE
ArgumentNullException after Ctrl+a Ctrl+x

### ISSUE THREAD

**Issue by JVimes** [PowerShell/PSReadLine#647]
This looks similar to #265 except different key combo, different exception, and not yet fixed.

Environment data
----------------

```
PS version: 5.1.17115.1
PSReadline version: 1.2
os: 10.0.17115.1 (WinBuild.160101.0800)
PS file version: 10.0.17115.1 (WinBuild.160101.0800)
```

Steps to reproduce or exception report
--------------------------------------

1. In an empty prompt, press `Ctrl+a` then `Ctrl+x`.

Result:
```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 2 Keys:
 Ctrl+a Ctrl+x

Exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: text
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at Microsoft.PowerShell.PSConsoleReadLine.Cut(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by lzybkr** [comment]
I think it has been fixed. Did you try [2.0.0-beta1](https://www.powershellgallery.com/packages/PSReadLine/2.0.0-beta1)?

**Comment by JVimes** [comment]
@lzybkr I didn't know about it. You're right. It's fixed in 2.0.0-beta1. Any idea how to get back to the production version of PowerShellGet and PSReadLine? I need to code against them. Thanks!

**Comment by lzybkr** [comment]
The versions installed with the OS are still installed - you can explicitly load those versions in your profile if you want to keep both on your system, otherwise just delete the newest version.

**Comment by JVimes** [comment]
Thanks. I seem to be back to normal after deleting the newer versions from `C:\Program Files\WindowsPowerShell\Modules`.

**Comment by LoganRsk** [comment]
I am on:
PSVersion                      5.1.17134.228
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.228
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

And I still have this issue, (actually I accidentally did [left arrow] then [ctrl+x].
It seems there's a bunch of errors with ctrl+x
ctrl+shift+left or right arrow and then ctrl+x also fails

**Comment by lzybkr** [comment]
@LoganRsk - do you have PSReadLine 2.0.0-beta1 or later?
